-- =====================================================
-- SUPABASE DATABASE SCHEMA FOR IMOTI HRISTOV
-- Run this in the Supabase SQL Editor
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- 1. BROKERS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.brokers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  image TEXT NOT NULL DEFAULT 'https://via.placeholder.com/200',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 2. PROPERTIES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.properties (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
  title VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(500) NOT NULL,
  city VARCHAR(100) NOT NULL,
  neighborhood VARCHAR(100),
  price DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(20) DEFAULT '€',
  price_per_sqm DECIMAL(10, 2),
  image TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  beds INTEGER,
  baths INTEGER,
  rooms INTEGER,
  floor VARCHAR(50),
  area DECIMAL(10, 2) NOT NULL,
  type VARCHAR(10) NOT NULL CHECK (type IN ('sale', 'rent')),
  category VARCHAR(100) NOT NULL,
  construction_type VARCHAR(50),
  is_new BOOLEAN DEFAULT false,
  is_top BOOLEAN DEFAULT false,
  is_recommended BOOLEAN DEFAULT false,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  date VARCHAR(20),
  features TEXT[] DEFAULT '{}',
  broker_id INTEGER REFERENCES public.brokers(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 3. CONTACT MESSAGES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  subject VARCHAR(100) DEFAULT 'general',
  message TEXT NOT NULL,
  gdpr_consent BOOLEAN DEFAULT false,
  is_read BOOLEAN DEFAULT false,
  property_id INTEGER REFERENCES public.properties(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 4. SITE SETTINGS TABLE (for future configurability)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.site_settings (
  id SERIAL PRIMARY KEY,
  key VARCHAR(100) UNIQUE NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 5. ADMIN USERS PROFILE TABLE (extends Supabase Auth)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.admin_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name VARCHAR(255),
  role VARCHAR(50) DEFAULT 'admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_properties_city ON public.properties(city);
CREATE INDEX IF NOT EXISTS idx_properties_type ON public.properties(type);
CREATE INDEX IF NOT EXISTS idx_properties_status ON public.properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_category ON public.properties(category);
CREATE INDEX IF NOT EXISTS idx_properties_is_recommended ON public.properties(is_recommended);
CREATE INDEX IF NOT EXISTS idx_contact_messages_is_read ON public.contact_messages(is_read);

-- =====================================================
-- UPDATED_AT TRIGGER FUNCTION
-- =====================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to tables with updated_at
DROP TRIGGER IF EXISTS update_properties_updated_at ON public.properties;
CREATE TRIGGER update_properties_updated_at
  BEFORE UPDATE ON public.properties
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_brokers_updated_at ON public.brokers;
CREATE TRIGGER update_brokers_updated_at
  BEFORE UPDATE ON public.brokers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_site_settings_updated_at ON public.site_settings;
CREATE TRIGGER update_site_settings_updated_at
  BEFORE UPDATE ON public.site_settings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brokers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;

-- PROPERTIES: Anyone can read active properties, only authenticated users can modify
CREATE POLICY "Anyone can view active properties" ON public.properties
  FOR SELECT USING (status = 'active' OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert properties" ON public.properties
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update properties" ON public.properties
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete properties" ON public.properties
  FOR DELETE USING (auth.role() = 'authenticated');

-- BROKERS: Anyone can read, only authenticated can modify
CREATE POLICY "Anyone can view brokers" ON public.brokers
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert brokers" ON public.brokers
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update brokers" ON public.brokers
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete brokers" ON public.brokers
  FOR DELETE USING (auth.role() = 'authenticated');

-- CONTACT MESSAGES: Anyone can insert, only authenticated can read/modify
CREATE POLICY "Anyone can submit contact messages" ON public.contact_messages
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Authenticated users can view contact messages" ON public.contact_messages
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update contact messages" ON public.contact_messages
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete contact messages" ON public.contact_messages
  FOR DELETE USING (auth.role() = 'authenticated');

-- SITE SETTINGS: Anyone can read, only authenticated can modify
CREATE POLICY "Anyone can view site settings" ON public.site_settings
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can modify site settings" ON public.site_settings
  FOR ALL USING (auth.role() = 'authenticated');

-- ADMIN PROFILES: Only the user themselves or authenticated admins
CREATE POLICY "Users can view own profile" ON public.admin_profiles
  FOR SELECT USING (auth.uid() = id OR auth.role() = 'authenticated');

CREATE POLICY "Users can update own profile" ON public.admin_profiles
  FOR UPDATE USING (auth.uid() = id);

-- =====================================================
-- STORAGE BUCKET FOR PROPERTY IMAGES
-- Run this separately in Supabase Storage settings or SQL
-- =====================================================
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('property-images', 'property-images', true)
-- ON CONFLICT (id) DO NOTHING;

-- Storage policy for property images
-- CREATE POLICY "Anyone can view property images" ON storage.objects
--   FOR SELECT USING (bucket_id = 'property-images');

-- CREATE POLICY "Authenticated users can upload property images" ON storage.objects
--   FOR INSERT WITH CHECK (bucket_id = 'property-images' AND auth.role() = 'authenticated');

-- CREATE POLICY "Authenticated users can update property images" ON storage.objects
--   FOR UPDATE USING (bucket_id = 'property-images' AND auth.role() = 'authenticated');

-- CREATE POLICY "Authenticated users can delete property images" ON storage.objects
--   FOR DELETE USING (bucket_id = 'property-images' AND auth.role() = 'authenticated');

-- =====================================================
-- SEED DATA - Initial brokers (optional)
-- =====================================================
INSERT INTO public.brokers (name, role, phone, email, image)
VALUES 
  ('Мария Петрова', 'Старши Брокер', '+359 888 123 456', 'maria@imotihristov.bg', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8Aa4UYur7AVUi8FL2A9QYMzhTnVp1vO78A7gAdrRxV9YvmXl1WEf_1eBDdSdQRkUxjPYULE-FF6xGCPHhd_cANI6muK86KgbVvaz6kf5smPCvHg-Y2tBuOUDtoLZnVgksANth6sAI7McdtfWKVSRnm3hdzQvbvHkjl9DeSxhKcA2LkZzTs_nAHUsIz5PwniMLqe65BvLykyl-Opr-FZnhiGw-VxrasY5S3OKLkrYNGbAVedy5fQb9W-AXzzBxnc-qIOx7KiEMRvE'),
  ('Георги Иванов', 'Брокер', '+359 887 654 321', 'georgi@imotihristov.bg', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjGEGbRnetogiiTaRl-dAsZryk48ms_fn3oYpfv_7pu-SVp1gRzWW4Shn3YJS7QFmfzugGCc_43OWpMRYqQSBXhjXPZZ0mievS6M67sm-1_TJxjg0TvvX4sKB-UyP4nIfb8q4VdxWfqzDk7QjBHq6Yn_sLENvTYM-hReGt8RaSlyeR4S1lbkLKtMFRZHkV5Iuf7mPDqRZYQR8X_b-EGkwM4B-EIMtuNwUHduNhqWSoLmTRMb1PAO2XnfI4OY74ewnJJbDfr098duY')
ON CONFLICT DO NOTHING;
